name: piece_racer
description: Competitive real-time puzzle racer built with Flutter and Firebase.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # State management and navigation
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.0

  # Firebase core stack
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.0.0
  google_fonts: ^8.0.2
  image_picker: ^1.2.1
  firebase_storage: ^13.0.6
  firebase_database: any
  shared_preferences: ^2.5.4
  freezed_annotation: ^3.1.0
  audioplayers: ^6.5.1
  confetti: ^0.8.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.11.1
  freezed: ^3.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
